# Generated by Django 5.2.4 on 2025-08-01 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('DEVOIR', 'Devoir'), ('QUIZ', 'Quiz')], max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.TextField()),
                ('type_question', models.CharField(choices=[('UNIQUE', 'Choix Unique'), ('MULTIPLE', 'Choix Multiple')], default='UNIQUE', max_length=10)),
                ('activite', models.ForeignKey(limit_choices_to={'activity_type': 'QUIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.activite')),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='evaluations.question')),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='soumissions/%Y/%m/%d/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('note', models.FloatField(blank=True, null=True)),
                ('activite', models.ForeignKey(limit_choices_to={'activity_type': 'DEVOIR'}, on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='evaluations.activite')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activite', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='Tentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(limit_choices_to={'activity_type': 'QUIZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='evaluations.activite')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activite', 'etudiant')},
            },
        ),
    ]
