# Generated by Django 5.2.4 on 2025-08-02 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='activity_type',
            field=models.CharField(choices=[('DEVOIR', 'Devoir'), ('QUIZ', 'Quiz'), ('SONDAGE', 'Sondage')], max_length=10),
        ),
        migrations.CreateModel(
            name='QuestionSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.TextField()),
                ('activite', models.ForeignKey(limit_choices_to={'activity_type': 'SONDAGE'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions_sondage', to='evaluations.activite')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_sondage', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.questionsondage')),
            ],
            options={
                'unique_together': {('question', 'etudiant')},
            },
        ),
    ]
