# Generated by Django 5.2.4 on 2025-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_activite_activity_type_questionsondage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='commentaires_enseignant',
            field=models.TextField(blank=True, null=True),
        ),
    ]
