# Generated by Django 5.2.4 on 2025-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='user',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='user',
            name='statut_enseignant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Statut Enseignant'),
        ),
    ]
