databases:
  - name: eistc-db
    databaseName: e_istc_db
    user: e_istc_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: e-istc-platform
    runtime: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn e_istc.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: eistc-db
          property: connectionString