# Generated by Django 5.2.4 on 2025-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_category_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
