# Generated by Django 5.2.4 on 2025-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_visio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visio_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
