# Generated by Django 5.2.4 on 2025-08-01 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SujetDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_crees', to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to='courses.course')),
            ],
            options={
                'ordering': ['-mis_a_jour_le'],
            },
        ),
        migrations.CreateModel(
            name='MessageForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_forum', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forums.sujetdiscussion')),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
    ]
