# Generated by Django 5.2.4 on 2025-08-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#0D47A1', max_length=7)),
                ('secondary_color', models.CharField(default='#FF9800', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
